### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by nordicroleplay** [MrDaGree/ELS-FiveM#74] opened 2020-06-23 20:33 UTC
### Bug Description

We tryed to update our ELS-script and found this, so I download the newest load I could find, Everything seemed to work absolutely fine just wrong xml files for the models. So I took our xml files and pasted that into vcf folder and deleted the original ones that was in the folder, than i renamed all xml names in vcf.lua to our file names.

### Screenshots

![els-problem](https://user-images.githubusercontent.com/65506037/85457373-4974af00-b5a0-11ea-95c8-72a3e02d85a5.png)

](url)### ELS Information
* Version #: 1.92
* Server Version #:  v1.0.0.2430 
* Screenshots of config.lua, vcf.lua, vcf folder:
![els-config 1](https://user-images.githubusercontent.com/65506037/85458482-76759180-b5a1-11ea-9d95-6d66e142caec.png)
![els-config 2](https://user-images.githubusercontent.com/65506037/85458488-79708200-b5a1-11ea-8b40-90048146af14.png)
![els-vcflua](https://user-images.githubusercontent.com/65506037/85458501-7d9c9f80-b5a1-11ea-86cf-2b481c36fff6.png)
![els-vcf](https://user-images.githubusercontent.com/65506037/85458515-7ffef980-b5a1-11ea-9094-315e090ad090.png)

**Comment by Zeemahh** [comment] 2020-06-23 20:39
Caused by some XML file not having an `Enabled` attribute within a `ForcedPatterns` element.

I have created a temp workaround fix for this.

**Closed** 2020-06-23 20:38 UTC
